ChatApplication/Models/User.cs
using System.ComponentModel.DataAnnotations;

namespace ChatApplication.Models
{
    public class User
    {
        [Key]
        public int id { get; set; }
        public string email { get; set; }
        public string username{ get; set; }
        public byte[] passwordHash { get; set; }
        public byte[] passwordSalt { get; set; }
    }
}

ChatApplication/Controllers/ChatController.cs
using ChatApplication.Hubs;
using ChatApplication.Models;
using ChatApplication.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.SignalR;

namespace ChatApplication.Controllers
{
    [Route("api/[controller]")]
    //[ApiController]
    public class ChatController : Controller
    {
        public readonly IHubContext<ChatHub> _hubContext;
        private readonly IUserService _userService;
        private readonly IChatService _chatService;
        private readonly IHttpContextAccessor _httpContextAccessor;
        private readonly IMessageService _messageService;
        public ChatController(
            IHubContext<ChatHub> hubContext, 
            IUserService userService, 
            IHttpContextAccessor httpContextAccessor,
            IChatService chatService,
            IMessageService messageService)
        {
            _hubContext = hubContext;
            _userService = userService;
            _httpContextAccessor = httpContextAccessor;
            _chatService = chatService;
            _messageService = messageService;
        }

        [HttpGet("test")]
        public IActionResult Index()
        {
            return View();
        }

        [HttpGet("OpenChatRoom")]
        public async Task<IActionResult> OpenChatRoom(int userId, string connectionId)
        {
            // Retrieve username from session
            string username = _httpContextAccessor.HttpContext.Session.GetString("Username");

            // Pass username to the layout view
            ViewBag.Username = username;
            
            var client = await _userService.GetClientName(userId);

            ViewBag.ClientId = client.userId;
            ViewBag.ClientName = client.username;
            ViewBag.ConnectionId = connectionId;

            var messages = await _messageService.GetMessages(username, client.username);

            return View(messages);
        }


        [HttpGet("OpenGroupChatRoom")]
        public async Task<IActionResult> OpenGroupChatRoom(int userId)
        {
            // Retrieve username from session
            string username = _httpContextAccessor.HttpContext.Session.GetString("Username");

            // Pass username to the layout view
            ViewBag.Username = username;

            var client = await _userService.GetClientName(userId);

            ViewBag.ClientId = client.userId;
            ViewBag.ClientName = client.username;

            var messages = await _messageService.GetMessages(username);

            return View(messages);
        }

        public record SendMessageDTO(string User, string ClientName, string Message);


        //Now need to pass username instead of hardcode receiverConnectionId, get username of chatroom
        //example: Hello! Welcome to the Chat Room of Client B (get client b username)
        //pass as parameter and read key of client b from db before sending message
        [HttpPost("send-message")]
        public async Task<IActionResult> SendToUser([FromBody] SendMessageDTO messageDTO)
        {
            try
            {
                // Call the service method to send the message
                string res = await _chatService.SendMessageToUser(messageDTO.User, messageDTO.ClientName, messageDTO.Message);
                //await _hubContext.Clients.Client(messageDTO.ReceiverConnectionId).SendAsync("ReceiveMessage", messageDTO.User, messageDTO.Message);

                if (res == "Message sent successfully") 
                {
                    return Ok();
                }
                else
                {
                    return BadRequest("Failed to send message");
                }
            }
            catch (Exception ex)
            {
                return StatusCode(500, $"Internal server error: {ex.Message}");
            }
        }

        /*
         * 1. create chat service to call hub and call service in SendToUser
         * 2. create user mapping bind key with the user (can create another table for that)
         * 2. save chat into database
         */

        public record SendMessageToAllDTO(string User, string Message);

        [HttpPost("send-message-to-all")]
        public async Task<IActionResult> SendMessage([FromBody] SendMessageToAllDTO messageDTO)
        {
            try
            {
                string res = await _chatService.SendMessageToGroup(messageDTO.User, messageDTO.Message);

                //await _hubContext.Clients.All.SendAsync("ReceiveMessage", messageDTO.User, messageDTO.Message);
                if (res == "Message sent successfully")
                {
                    return Ok();
                }
                else
                {
                    return BadRequest("Failed to send message");
                }
            }
            catch (Exception ex)
            {
                return StatusCode(500, $"Internal server error: {ex.Message}");
            }
        }
    }
}

ChatApplication/Controllers/UserController.cs
using ChatApplication.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.IdentityModel.Tokens.Jwt;
using System.Security.Claims;
using System.Xml.Linq;

namespace ChatApplication.Controllers
{
    [Route("api/[controller]")]
    public class UserController : Controller
    {
        private readonly IUserService _userService;
        private readonly IHttpContextAccessor _httpContextAccessor;
        public UserController(IUserService userService, IHttpContextAccessor httpContextAccessor)
        {
            _userService = userService;
            _httpContextAccessor = httpContextAccessor;

        }

        public async Task<IActionResult> Index()
        {
            // Retrieve username from session
            
            string username = _httpContextAccessor.HttpContext.Session.GetString("Username");
            int userId = await _userService.GetUserId(username);

            // Pass username to the layout view
            ViewBag.Username = username;
            ViewBag.UserId = userId;

            var res = await _userService.GetAllUsers();
            return View(res);
        }

        [HttpGet("get-username")]
        public async Task<string> GetUsername()
        {
            var username = _httpContextAccessor.HttpContext.Session.GetString("Username");
            return username;
            //var handler = new JwtSecurityTokenHandler();
            //var jsonToken = handler.ReadToken(token) as JwtSecurityToken;

            //string Name = jsonToken?.Claims.FirstOrDefault(claim => claim.Type == "name")?.Value!;

            //if (Name != null)
            //{
            //    string username = Name;
            //    return Ok(username);
            //}
            //else
            //{
            //    // Username claim not found in the token
            //    return BadRequest("Username claim not found in the token.");
            //}
        }

    }
}

ChatApplication/Views/User/Index.cshtml
@model IEnumerable<ChatApplication.Viewmodels.UserViewModelDTO>

@{
    ViewBag.Title = "Index";
}

@* <p class="btn btn-sm">
    @Html.ActionLink("Add", "AddCategory", "Category", "", new { @class = "btn btn-sm btn-primary" })
</p> *@
@{
    var username = ViewBag.Username;
    var userId = ViewBag.UserId;
}


<div class="">

    <h2 style="text-align:center;
        font-weight:bold">
        Users
    </h2>

    <div class="row">

        @foreach (var item in Model)
        {
            @*  <li>@item.username | @Html.ActionLink("Open Chat", "OpenChatRoom", "Chat",
        new { userId = item.userId }, new { @class = "btn btn-sm btn-dark" })
        </li> *@

            <div class="col-md-6">
                <p style="text-align:right">
                    @item.username
                    @*  <a class="btn btn-sm btn-dark"
                onclick="Connect('@username', event)">Connect</a> *@

                </p>
            </div>
            <div class="col-md-6">
                <p>
                    @Html.ActionLink("Open Chat", "OpenChatRoom", "Chat",
                             new { userId = item.userId }, new { @class = "btn btn-primary" })
                </p>
            </div>
        }

        <div class="col-md-6">
            <p style="text-align:right">
                Group
            </p>
        </div>
        <div class="col-md-6">
            <p>
                @Html.ActionLink("Open Chat", "OpenGroupChatRoom", "Chat",
                         new { userId = @userId }, new { @class = "btn btn-primary" })
            </p>
        </div>
    </div>
</div>

<script>

    function OpenChatroom(userId) {
        // Make AJAX call to the backend method and include the connection ID in the data parameter
        $.ajax({
            url: '/api/Chat/OpenChatRoom',
            data: { userId: userId }, //connectionId: connectionId, Include the connection ID in the data parameter
            method: 'GET',
            success: function (response) {
                // Handle the success response from the backend method
                console.log('Backend method call successful');
            },
            error: function (xhr, status, error) {
                // Handle the error response from the backend method
                console.error('Backend method call failed:', error);
            }
        });
    }

    function Connect(username, event) {
        // Invoke GetUsernameAsync method on the SignalR connection
        connection.invoke("GetUsernameAsync", username)
            .then(function (connectionId) {
                console.log("Last generated connection ID:", connectionId);
            })
            .catch(function (err) {
                console.error(err.toString());
            });

        // Prevent the default action of the link (navigation)
        //event.preventDefault();

        // $.ajax({
        //     url: '/api/Chat/OpenChatRoom',
        //     data: { userId: userId, connectionId: connectionId },
        //     method: 'GET',
        //     success: function (response) {
        //         // Handle the success response from the backend method
        //         console.log('Backend method call successful');
        //     },
        //     error: function (xhr, status, error) {
        //         // Handle the error response from the backend method
        //         console.error('Backend method call failed:', error);
        //     }
        // });

    }
</script>
@* <table class="table">
    <thead>
        <tr>
            <th>
                Category Name
            </th>
            <th>
                Description
            </th>
            <th>
                Status
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.categoryName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.description)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.isActive)
                </td>
                <td>
                    @Html.ActionLink("Edit", "UpdateCategory", new { id = item.categoryId }, new { @class = "btn btn-sm btn-dark" })
                    @Html.ActionLink("Delete", "DeleteCategory", new { id = item.categoryId }, new { @class = "btn btn-sm btn-danger" })
                </td>

            </tr>
        }
    </tbody>
</table> *@